FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-devel
ENV CMAKE_POLICY_VERSION_MINIMUM=3.5
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    git \
    libgl1 \
    libglib2.0-0 \
    zip \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get install -y libgtk2.0-dev wget bzip2 ca-certificates curl git vim tmux \
    g++ gcc build-essential cmake checkinstall gfortran libjpeg8-dev libtiff5-dev \
    pkg-config yasm libavcodec-dev libavformat-dev libswscale-dev libxine2-dev \
    libv4l-dev libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev \
    libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev \
    libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler \
    libgoogle-glog-dev libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev \
    libboost-all-dev proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui \
    libzmq3-dev freeglut3-dev libxrender1 libxext6 libsm6 libx11-6 libegl1-mesa \
    libgles2-mesa libgbm1

RUN cd / && git clone https://github.com/pybind/pybind11 && \
    cd pybind11 && git checkout v2.10.0 && \
    mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF && \
    make -j6 && make install

RUN cd / && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar xvzf ./eigen-3.4.0.tar.gz && \
    cd eigen-3.4.0 && \
    mkdir build && cd build && cmake .. && make install

RUN pip install \
    scipy \
    joblib \
    scikit-learn \
    ruamel.yaml \
    trimesh \
    pyyaml \
    opencv-python \
    imageio \
    open3d \
    transformations \
    warp-lang \
    einops \
    kornia \
    pyrender

RUN pip install kaolin==0.18.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.8.0_cu128.html

RUN TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0 12.0" pip3 install "git+https://github.com/facebookresearch/pytorch3d.git"

RUN git clone https://github.com/NVlabs/nvdiffrast /workspace/third_party/nvdiffrast && \
    cd /workspace/third_party/nvdiffrast && \
    pip install setuptools wheel ninja && \
    TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0 12.0" pip install . --no-build-isolation

ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN pip install \
    scikit-image \
    meshcat \
    webdataset \
    omegaconf \
    pypng \
    roma \
    seaborn \
    opencv-contrib-python \
    openpyxl \
    wandb

RUN pip install h5py fast_simplification gdown

COPY v2d_foundation_pose/lib/FoundationPose/mycpp /workspace/v2d_foundation_pose/lib/FoundationPose/mycpp
COPY v2d_foundation_pose/lib/FoundationPose/bundlesdf/mycuda /workspace/v2d_foundation_pose/lib/FoundationPose/bundlesdf/mycuda

RUN cd /workspace/v2d_foundation_pose/lib/FoundationPose/mycpp \
    && mkdir -p build && cd build && cmake .. -DPYTHON_EXECUTABLE=$(which python) && make -j11

RUN cd /workspace/v2d_foundation_pose/lib/FoundationPose/bundlesdf/mycuda && \
    TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0 12.0" pip install -e .

COPY . /workspace

RUN pip install -e "/workspace/v2d_common[io]" \
    -e "/workspace/v2d_mv[math]" \
    -e /workspace/v2d_mesh/lib -e /workspace/v2d_foundation_pose/lib

# Verify the torch in the finished image can actually run on the architectures
# this image was built for, and repair it if some dependency replaced it.
RUN P="$(command -v python || command -v python3)"; \
    "$P" -c "import importlib.util as u, sys; \
sys.exit(0) if u.find_spec('torch') is None else None; \
import torch; \
sys.exit(3 if 'sm_120' not in torch.cuda.get_arch_list() else 0)" \
    || "$P" -m pip install --no-cache-dir --force-reinstall \
        torch==2.8.0 torchvision==0.23.0 \
        --index-url https://download.pytorch.org/whl/cu128
